import "./globals.css";
import { Poppins } from "next/font/google";
import { Metadata } from "next";

import ThemeWrapper from "./ThemeWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Better To-Do List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeWrapper>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
