import "./globals.css";
import { Metadata } from "next";

import ThemeWrapper from "./ThemeWrapper";
import { poppins } from "./fonts";
import { AppProvider } from "@/context/AppProvider";

export const metadata: Metadata = {
  title: "Better To-Do List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppProvider>
          <ThemeWrapper>{children}</ThemeWrapper>
        </AppProvider>
      </body>
    </html>
  );
}
