"use client";
import { Main } from "@/styles/sharedStyles";
import { Metadata } from "next";
import homeImg from "../../public/img/b.svg";
import Image from "next/image";
import styled from "styled-components";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Better To-Do List",
  description: "Generated by create next app",
};

const Buttons = styled.div`
  display: flex;
  justify-content: center;
  gap: 2rem;
  margin-top: 2rem;
`;

const TextDiv = styled.div`
  text-align: center;
  font-size: 1.2rem;
  margin-top: 2rem;

  p {
    font-weight: bold;
  }

  @media (min-width: 600px) {
    font-size: 1.5rem;
  }

  @media (min-width: 992px) {
    font-size: 2rem;
    margin-top: 0;
  }
`;

const StyledImage = styled(Image)`
  width: 300px;
  height: 300px;

  @media (min-width: 768px) {
    width: 400px;
    height: 400px;
  }

  @media (min-width: 992px) {
    width: 500px;
    height: 500px;
  }
`;

const StyledLink = styled(Link)`
  text-transform: uppercase;
  padding: 0.5rem 2rem;
  font-size: 1rem;
  background-color: ${(p) => p.theme.primaryColor};
  color: #fff;
  border-radius: 0.5rem;
  transition-duration: 0.3s;

  @media (min-width: 768px) {
    font-size: 1.3rem;
  }

  &:hover {
    background-color: ${(p) => p.theme.secondaryColor};
  }
`;

const page = () => {
  return (
    <Main>
      <StyledImage src={homeImg} height={500} width={500} alt="Home Image" />
      <TextDiv>
        <p>Access to maximize your productivity.</p>
        <p>Organize, accomplish, triumph!</p>

        <Buttons>
          <StyledLink href="/login">login</StyledLink>
          <StyledLink href="/register">register</StyledLink>
        </Buttons>
      </TextDiv>
    </Main>
  );
};

export default page;
