"use client";
import { Metadata } from "next";
import Login from "@/components/Login/Login";

export const metadata: Metadata = {
  title: "Better To-Do List",
  description: "Generated by create next app",
};

const page = () => {
  return <Login />;
};

export default page;
