"use client";
import { Container } from "@/styles/sharedStyles";
import { Metadata } from "next";
import Sidebar from "../components/Sidebar/Sidebar";
import Login from "../components/Login/Login";

export const metadata: Metadata = {
  title: "Better To-Do List",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Container>
      <Sidebar />

      <Login />
    </Container>
  );
};

export default page;
